In [1]:
import pandas as pd
data={
    'Department':['HR','Sales','IT','Sales','IT','HR','Sales'],
    'Employee':['A','B','C','D','E','F','G'],
    'Salary':[50000,60000,45000,48000,70000,72000,71000],
    'Experience':[2,4,3,5,6,7,5]
}
df=pd.DataFrame(data)
print(df)

  Department Employee  Salary  Experience
0         HR        A   50000           2
1      Sales        B   60000           4
2         IT        C   45000           3
3      Sales        D   48000           5
4         IT        E   70000           6
5         HR        F   72000           7
6      Sales        G   71000           5

In [4]:
df.groupby(['Department','Experience']).sum()

                      Employee  Salary
Department Experience
HR         2                 A   50000
           7                 F   72000
IT         3                 C   45000
           6                 E   70000
Sales      4                 B   60000
           5                DG  119000

In [5]:
df.groupby(['Department','Experience'])

In [6]:
df3=df.groupby(['Department','Experience']).sum()
print(df3)

                      Employee  Salary
Department Experience
HR         2                 A   50000
           7                 F   72000
IT         3                 C   45000
           6                 E   70000
Sales      4                 B   60000
           5                DG  119000

In [7]:
df.groupby('Department')['Salary'].sum()

Department
HR       122000
IT       115000
Sales    179000
Name: Salary, dtype: int64

In [21]:
df1=df.groupby(['Department','Experience']).sum()
print(df1)

                      Employee  Salary  Dept_Avg_Salary
Department Experience
HR         2                 A   50000     61000.000000
           7                 F   72000     61000.000000
IT         3                 C   45000     57500.000000
           6                 E   70000     57500.000000
Sales      4                 B   60000     59666.666667
           5                DG  119000    119333.333333

In [9]:
df2=df.groupby('Department').sum()
print(df2)

           Employee  Salary  Experience
Department
HR               AF  122000           9
IT               CE  115000           9
Sales           BDG  179000          14

In [10]:
df5=df.groupby('Department')['Salary'].mean()
print(df5)

Department
HR       61000.000000
IT       57500.000000
Sales    59666.666667
Name: Salary, dtype: float64

In [12]:
df6=df.groupby('Department')['Employee'].count()
print(df6)

Department
HR       2
IT       2
Sales    3
Name: Employee, dtype: int64

In [14]:
df7=df.groupby('Department')['Salary'].agg(['sum','mean','std'])
print(df7)

               sum          mean           std
Department
HR          122000  61000.000000  15556.349186
IT          115000  57500.000000  17677.669530
Sales       179000  59666.666667  11503.622618

In [15]:
df.groupby('Department').agg({
    'Salary':'sum','Experience':'mean'
})

            Salary  Experience
Department
HR          122000    4.500000
IT          115000    4.500000
Sales       179000    4.666667

In [18]:
df9=df['Dept_Avg_Salary']=df.groupby('Department')['Salary'].transform('mean')
print(df9)

0    61000.000000
1    59666.666667
2    57500.000000
3    59666.666667
4    57500.000000
5    61000.000000
6    59666.666667
Name: Salary, dtype: float64

In [19]:
df1=df.groupby('Department').filter(lambda x:len(x)>2)
print(df1)

  Department Employee  Salary  Experience  Dept_Avg_Salary
1      Sales        B   60000           4     59666.666667
3      Sales        D   48000           5     59666.666667
6      Sales        G   71000           5     59666.666667

In [22]:
df.pivot_table(
    values='Salary',
    index='Department',
    columns='Experience',
    aggfunc='mean'

)

Experience        2        3        4        5        6        7
Department
HR          50000.0      NaN      NaN      NaN      NaN  72000.0
IT              NaN  45000.0      NaN      NaN  70000.0      NaN
Sales           NaN      NaN  60000.0  59500.0      NaN      NaN

In [24]:
import pandas as pd
data={
    'Crop':['rice','wheat','ragi','rice','ragi','wheat','rice'],
    'season':['kharif','rabi','kharif','rabi','rabi','kharif','kharif'],
    'fertilizer':[100,120,150,160,200,220,180],
    'yield':[25,28,31,27,32,29,26]
}
df=pd.DataFrame(data)
print(df)

    Crop  season  fertilizer  yield
0   rice  kharif         100     25
1  wheat    rabi         120     28
2   ragi  kharif         150     31
3   rice    rabi         160     27
4   ragi    rabi         200     32
5  wheat  kharif         220     29
6   rice  kharif         180     26

In [25]:
df.groupby(['Crop','yield']).sum()

             season  fertilizer
Crop  yield
ragi  31     kharif         150
      32       rabi         200
rice  25     kharif         100
      26     kharif         180
      27       rabi         160
wheat 28       rabi         120
      29     kharif         220

In [27]:
df3=df.groupby('fertilizer').sum()
print(df3)

             Crop  season  yield
fertilizer
100          rice  kharif     25
120         wheat    rabi     28
150          ragi  kharif     31
160          rice    rabi     27
180          rice  kharif     26
200          ragi    rabi     32
220         wheat  kharif     29

In [28]:
df.groupby('Crop')['fertilizer'].sum()

Crop
ragi     350
rice     440
wheat    340
Name: fertilizer, dtype: int64

In [29]:
df1=df.groupby(['Crop','season']).sum()
print(df1)

              fertilizer  yield
Crop  season
ragi  kharif         150     31
      rabi           200     32
rice  kharif         280     51
      rabi           160     27
wheat kharif         220     29
      rabi           120     28

In [30]:
df2=df.groupby('Crop').sum()
print(df2)

                 season  fertilizer  yield
Crop
ragi         kharifrabi         350     63
rice   kharifrabikharif         440     78
wheat        rabikharif         340     57

In [32]:
df5=df.groupby('Crop')['yield'].mean()
print(df5)

Crop
ragi     31.5
rice     26.0
wheat    28.5
Name: yield, dtype: float64

In [33]:
df6=df.groupby('Crop')['yield'].count()
print(df6)

Crop
ragi     2
rice     3
wheat    2
Name: yield, dtype: int64

In [34]:
df7=df.groupby('Crop')['yield'].agg(['sum','mean','std'])
print(df7)

       sum  mean       std
Crop
ragi    63  31.5  0.707107
rice    78  26.0  1.000000
wheat   57  28.5  0.707107

In [36]:
df.groupby('Crop').agg({
    'fertilizer': 'sum',
    'yield': 'mean'
})

       fertilizer  yield
Crop
ragi          350   31.5
rice          440   26.0
wheat         340   28.5

In [37]:
df9=df['Crop_Avg_Yield']=df.groupby('Crop')['yield'].transform('mean')
print(df9)

0    26.0
1    28.5
2    31.5
3    26.0
4    31.5
5    28.5
6    26.0
Name: yield, dtype: float64

In [38]:
df1=df.groupby('Crop').filter(lambda x:len(x)>2)
print(df1)

   Crop  season  fertilizer  yield  Crop_Avg_Yield
0  rice  kharif         100     25            26.0
3  rice    rabi         160     27            26.0
6  rice  kharif         180     26            26.0

In [41]:
df.pivot_table(
    values='yield',
    index='Crop',
    columns='fertilizer',
    aggfunc='mean'
)

fertilizer   100   120   150   160   180   200   220
Crop
ragi         NaN   NaN  31.0   NaN   NaN  32.0   NaN
rice        25.0   NaN   NaN  27.0  26.0   NaN   NaN
wheat        NaN  28.0   NaN   NaN   NaN   NaN  29.0